services:
  collator-01:
    image: mangatasolutions/mangata-node:eth-rollup-develop
    restart: unless-stopped
    platform: linux/amd64
    entrypoint: ['/bin/bash']
    command:
      - -c
      - |
        set -eu
        /mangata/node export-genesis-state --chain=mangata-rococo-local > /data/genesis-state
        /mangata/node export-genesis-wasm --chain=mangata-rococo-local > /data/genesis-wasm
        /mangata/node key insert --chain=mangata-rococo-local \
          --keystore-path /data/keystore \
          --key-type aura \
          --scheme sr25519 \
          --suri '0xe5be9a5092b81bca64be81d212e7f2f9eba183bb7a90954f7b76361f6edb5c0a' \
          && echo "Inserted Account key into Keystore"
        exec /mangata/node \
          --name collator-01 \
          --collator \
          --chain=mangata-rococo-local \
          --base-path=/data \
          --keystore-path /data/keystore \
          --node-key 5ad94653edf592f59d1b54960cda1334596cc3dcab8dd96adb334d3e22e912ef \
          --rpc-cors=all \
          --rpc-port=9944 \
          --port=30333 \
          --rpc-methods=unsafe \
          --unsafe-rpc-external \
          -- \
          --chain=/etc/rococo-local-chainspec.json \
          --bootnodes=/dns/relay-alice/tcp/30333/p2p/12D3KooWLKDfMrz5MvJzNe2YUd1WxtPErqKD2Nh5tzhPi28qAcTU
      - "9944:9944"
    volumes:
      - collator-01-data:/data
      - ./rococo-local-chainspec.json:/etc/rococo-local-chainspec.json
  
  collator-02:
    image: mangatasolutions/mangata-node:eth-rollup-develop
    restart: unless-stopped
    platform: linux/amd64
    entrypoint: ['/bin/bash']
    command:
      - -c
      - |
        set -eu
        /mangata/node key insert --chain=mangata-rococo-local \
          --keystore-path /data/keystore \
          --key-type aura \
          --scheme sr25519 \
          --suri '0x398f0c28f98885e046333d4a41c19cee4c37368a9832c6502f6cfd182e2aef89' \
          && echo "Inserted Account key into Keystore"
        exec /mangata/node \
          --name collator-02 \
          --collator \
          --chain=mangata-rococo-local \
          --base-path=/data \
          --keystore-path /data/keystore \
          --node-key bcaf1bb787b48156aadaf318603e5b37e637883edafb850912e364e913e2c35b \
          --rpc-cors=all \
          --rpc-port=9944 \
          --port=30333 \
          --rpc-methods=unsafe \
          --unsafe-rpc-external \
          --bootnodes /dns/collator-01/tcp/30333/p2p/12D3KooWAfm5cK7DuUa2zh9SrSoHr2fsXXYbLALWXs5ob9mTDKHJ \
          -- \
          --chain=/etc/rococo-local-chainspec.json \
          --bootnodes=/dns/relay-alice/tcp/30333/p2p/12D3KooWLKDfMrz5MvJzNe2YUd1WxtPErqKD2Nh5tzhPi28qAcTU
      - "9945:9944"
    volumes:
      - collator-02-data:/data
      - ./rococo-local-chainspec.json:/etc/rococo-local-chainspec.json
    
  parachain-register:
    image: mangatasolutions/parachain-register:1.1
    restart: unless-stopped
    platform: linux/amd64
    environment:
      - STATE_FILE=/data/genesis-state
      - WASM_FILE=/data/genesis-wasm
      - COLLATOR_ADDR=ws://relay-alice:9944
      - PARA_ID=2110
    volumes:
      - collator-01-data:/data
    depends_on: ['collator-01']

  relay-alice:
    image: parity/polkadot:v1.1.0
    restart: unless-stopped
    platform: linux/amd64
    command:
      - --alice
      - --validator
      - --chain=rococo-local
      - --rpc-port=9944
      - --port=30333
      - --rpc-cors=all
      - --base-path=/data
      - --unsafe-rpc-external
      - --rpc-methods=unsafe
    ports:
      - "9946:9944"
    volumes:
      - relay-alice-data:/data
  
  relay-bob:
    image: parity/polkadot:v1.1.0
    restart: unless-stopped
    platform: linux/amd64
    command:
      - --bob
      - --validator
      - --bootnodes=/dns/relay-alice/tcp/30333/p2p/12D3KooWNohGc5PznWzjkmRWdgJAxyrN8xx8qAgDWkkBWjAMv5R6
      - --chain=rococo-local
      - --rpc-port=9944
      - --port=30333
      - --rpc-cors=all
      - --base-path=/data
      - --unsafe-rpc-external
      - --rpc-methods=unsafe
    ports:
      - "9947:9944"
    volumes:
      - relay-bob-data:/data


volumes:
  collator-01-data:
  collator-02-data:
  relay-alice-data:
  relay-bob-data: