version: '3.8'

services:
  anvil:
    image: ghcr.io/foundry-rs/foundry
    ports:
      - "8545:8545"
    # changed entrypoint because the default 'bash -c' entrypoint wasn't working the intended way...
    entrypoint: anvil
    volumes:
      - ./tests/integration/avs-and-eigenlayer-deployed-anvil-state.json:/root/.anvil/state.json
    command: --host 0.0.0.0 --load-state /root/.anvil/state.json
    healthcheck:
      test: ["CMD", "nc", "-vz", "localhost", "8545"]
      interval: 2s
      timeout: 10s
      retries: 3

  aggregator:
    image: mangatasolutions/aggregator:latest
    build:
      context: .
      dockerfile: aggregator/Dockerfile
    depends_on:
      anvil:
        condition: service_healthy
    ports:
      - 8090:8090
    volumes:
      - ./:/app
    command:
      - --config 
      # - config-files/aggregator.yaml
      - config-files/aggregator-docker-compose.yaml
      - --credible-squaring-deployment 
      - contracts/script/output/31337/credible_squaring_avs_deployment_output.json
      - --shared-avs-contracts-deployment 
      - contracts/script/output/31337/shared_avs_contracts_deployment_output.json
      - --ecdsa-private-key 
      - "0x2a871d0798f97d79848a013d4936a73bf4cc922c825d33c1cf7073dff6d409c6"

  operator:
    image: mangatasolutions/operator:latest
    build:
      context: .
      dockerfile: operator/Dockerfile
    depends_on: ['anvil', 'aggregator']
    ports:
      - 9010:9010
      - 9090:9090
    volumes:
      - ./:/app
    command: --config config-files/operator-docker-compose.anvil.yaml
