services:
  updater-eth:
    restart: unless-stopped
    image: mangatasolutions/rollup-updater:${ROLLUP_UPDATER_VERSION:-local}
    build: .
    depends_on:
      eth-contracts-deployment:
        condition: service_completed_successfully
      node-alice:
        condition: service_started
    environment:
      L1_CHAIN: "Ethereum"
      MANGATA_NODE_URL: ${ROLLUP_UPDATER_MANGATA_NODE_URL:-wss://collator-01-ws-rococo.mangata.online}
      ETH_CHAIN_URL: ${ROLLUP_UPDATER_ETH_CHAIN_URL:-wss://ethereum.publicnode.com}
      FINALIZATION_SOURCE: ${ROLLUP_UPDATER_FINALIZATION_SOURCE:-relay}
      # Defaults to one of anvil default accounts private key
      WALLET_PRIVATE_KEY: ${ROLLUP_UPDATER_WALLET_PRIVATE_KEY:-0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80}
      VERBOSE: 1
      EIGEN_CONTRACT_ADDRESS: "0x1613beB3B2C4f22Ee086B2b38C1476A3cE7f78E8"
      MANGATA_CONTRACT_ADDRESS: ${MANGATA_CONTRACT_ADDRESS:-0x7bc06c482DEAd17c0e297aFbC32f6e63d3846650}

  updater-arb:
    restart: unless-stopped
    image: mangatasolutions/rollup-updater:${ROLLUP_UPDATER_VERSION:-local}
    build: .
    depends_on:
      arbitrum-contracts-deployment:
        condition: service_completed_successfully
      node-alice:
        condition: service_started
    environment:
      L1_CHAIN: "Arbitrum"
      MANGATA_NODE_URL: ${ROLLUP_UPDATER_MANGATA_NODE_URL:-wss://collator-01-ws-rococo.mangata.online}
      ETH_CHAIN_URL: ${ROLLUP_UPDATER_ARB_CHAIN_URL:-wss://ethereum.publicnode.com}
      FINALIZATION_SOURCE: ${ROLLUP_UPDATER_FINALIZATION_SOURCE:-relay}
      # Defaults to one of anvil default accounts private key
      WALLET_PRIVATE_KEY: ${ROLLUP_UPDATER_WALLET_PRIVATE_KEY:-0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80}
      VERBOSE: 1
      EIGEN_CONTRACT_ADDRESS: "0x1613beB3B2C4f22Ee086B2b38C1476A3cE7f78E8"
      MANGATA_CONTRACT_ADDRESS: ${MANGATA_CONTRACT_ADDRESS:-0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9}
