remoteCluster: true

anvilEnabled: true
aggregatorEnabled: true
operatorEnabled: true
updaterEnabled: true
sequencerEnabled: true

env:
  # rpc
  ETH_RPC_URL: http://anvil:8545
  ETH_WS_URL: ws://anvil:8545
  SUBSTRATE_RPC_URL: wss://kusama-archive.mangata.online:443
  # contracts
  CHAIN_ID: '"31337"'
  BLS_COMPENDIUM_ADDR: 0xc5a5C42992dECbae36851359345FE25997F5C42d
  BLS_OPERATOR_STATE_RETRIEVER_ADDR: 0x67d269191c92Caf3cD7723F116c85e6E9bf55933
  AVS_SERVICE_MANAGER_ADDR: 0x9E545E3C0baAB3E08CdfD552C960A1050f373042
  # keys
  ECDSA_KEY_FILE: /config/ecdsa.key.json
  BLS_KEY_FILE: /config/bls.key.json
  # AVS
  AVS_SERVER_IP_PORT_ADDRESS: 0.0.0.0:8090
  AVS_BLOCK_VALIDATION_PERIOD: '"5"'
  # OP
  AVS_RPC_URL: http://eigen-aggregator:8090
  REGISTER_AT_STARTUP: "'true'"

envSecrets:

aggregatorConfigFiles:
  - name: ecdsa.key.json
    content: |
      {"address":"a0ee7a142d267c1f36714e4a8f75612f20a79720","crypto":{"cipher":"aes-128-ctr","ciphertext":"b0f6f8e3ba33f0b382b080de6661d827181de480f1a4f94bc20d66cb3d585907","cipherparams":{"iv":"4e3f9a8ca6ef8d1cd408e8aaae3c22d2"},"kdf":"scrypt","kdfparams":{"dklen":32,"n":262144,"p":1,"r":8,"salt":"c8f9f8cc03913e09cee7e1fd68732fac327576203ab277d740270f1dea82ee7e"},"mac":"353d65850b20d5fdb90ca2385c52e5b57662cb1d906fd58143f20a7720723cf6"},"id":"d3036cc7-d068-4f2f-9667-60aaca660e61","version":3}

operatorEnableServiceMonitorCollectors: false
operatorConfigFiles:
  - name: ecdsa.key.json
    content: |
      {"address":"860b6912c2d0337ef05bbc89b0c2cb6cbaeab4a5","crypto":{"cipher":"aes-128-ctr","ciphertext":"37ab29382354906d7b33b0ad1b00c539dfb69ea85997e470baba7601b0faa373","cipherparams":{"iv":"b7642683ba782688cc4da76dd5c61fce"},"kdf":"scrypt","kdfparams":{"dklen":32,"n":262144,"p":1,"r":8,"salt":"fdc108d3e6388174f4cf6d5abe6de2364c96dcc03c4f1bddb1b47b01dce742e2"},"mac":"d4fff8d963a7815a7203f8c73b3047a2e5efcefb8163e6df316cc55f79df0cc2"},"id":"0c401f60-9d1f-4918-a823-1866984f8fcd","version":3}
  - name: bls.key.json
    content: |
      {"pubKey":"E([643552363890320897587044283125191574906281609959531590546948318138132520777,7028377728703212953187883551402495866059211864756496641401904395458852281995])","crypto":{"cipher":"aes-128-ctr","ciphertext":"8221f69293d98ca9d46c52a2747b61755c6bb71f41e951154af3bcbc0daef2b8","cipherparams":{"iv":"d8a38c68f3400aeb93084672b6e3ae61"},"kdf":"scrypt","kdfparams":{"dklen":32,"n":262144,"p":1,"r":8,"salt":"c41150482e6acfc2f0fcfd68b67f28ef22de8aa3f982048bdaf793c2e3ac3730"},"mac":"879c2831169d9ac70c662ebca90b9f3cd63761d0924bdbbde0a82a306baf44cd"}}