remoteCluster: true

anvilEnabled: false
aggregatorEnabled: true
operatorEnabled: false
updaterEnabled: false
sequencerEnabled: false

envSecrets:
  ECDSA_KEY_JSON: ref+gcpsecrets://direct-pixel-353917/eigen-goerli-aggregator-ecdsa-key
  ECDSA_KEY_PASSWORD: ''

env:
  ETH_RPC_URL: ref+gcpsecrets://direct-pixel-353917/eigen-goerli-rpc-url
  ETH_WS_URL: ref+gcpsecrets://direct-pixel-353917/eigen-goerli-ws-url
  # rpc
  SUBSTRATE_RPC_URL: wss://kusama-archive.mangata.online
  # contracts
  CHAIN_ID: 5
  BLS_COMPENDIUM_ADDR: 0xc81d3963087Fe09316cd1E032457989C7aC91b19
  BLS_OPERATOR_STATE_RETRIEVER_ADDR: 0x737Dd62816a9392e84Fa21C531aF77C00816A3a3
  AVS_SERVICE_MANAGER_ADDR: 0xD2333E11ea617E30fb97900f6ac9782A85f233e7
  # AVS
  AVS_SERVER_IP_PORT_ADDRESS: 0.0.0.0:8090
  AVS_BLOCK_VALIDATION_PERIOD: 10
