remoteCluster: true

blockscoutEnabled: false
enableArbitrumServices: true

####################
# evm-node configs #
####################
evmNode:
  enabled: false

#####################
# collator configs #
#####################
collatorsEnabled: true
collator:
  image:
    repository: mangatasolutions/rollup-node
    tag: frontend-fix
  disableChainspecGeneration: true
  customChainspecUrl: https://raw.githubusercontent.com/mangata-finance/chainspec/e6dbb96641a79a8d77c2ce79c20c1ed598958f00/rollup-holesky-3a07824d8b8a6ad027424629b814a5edb61654cf-raw.json
  enableServiceMonitorCollectors: true
  storageClass: node-data-volume-retain
  storageSize: 50Gi
  wsHealthExporter:
    enabled: true
    image: paritytech/ws-health-exporter:bc071a44-20230830
    env:
      WSHE_NODE_MIN_PEERS: 2
  tolerations:
    - key: production
      operator: Equal
      value: "true"
      effect: NoSchedule
  # Node specific collator configs
  collator01:
    # Identity ID: 12D3KooWQVtLSDM8ZuaExjLygBKBjA43gKUZH3wiooxs7Qp7iEQK
    customNodeKey: '5f982f7cd04dde558ae7800d4cf2facd0a4e0c64f627db666456ad903077e6da'
    bootnodeAddr: /dns/collator-02-p2p/tcp/30333/p2p/12D3KooWNVGLHURQs8NqYGrLnpoSePh5QPjBqUJDJL8CmNgr4qWN
    extraArgs:
      - --alith
      - --pruning=archive
      - --rpc-max-connections=5000
    nodeSelector:
      production: "true"
      topology.kubernetes.io/zone: europe-west1-b
  collator02:
    # Identity ID: 12D3KooWNVGLHURQs8NqYGrLnpoSePh5QPjBqUJDJL8CmNgr4qWN
    customNodeKey: '2747e7dadbc3a7cc50e678a9f264cb385852a8883cac4d4d016afc0b8513a6f9'
    bootnodeAddr: /dns/collator-01-p2p/tcp/30333/p2p/12D3KooWQVtLSDM8ZuaExjLygBKBjA43gKUZH3wiooxs7Qp7iEQK
    extraArgs:
      - --baltathar
      - --pruning=archive
      - --rpc-max-connections=5000
    nodeSelector:
      production: "true"
      topology.kubernetes.io/zone: europe-west1-c

####################
# evm-node configs #
####################
envEth:
  # rpc
  ETH_RPC_URL: http://evm-node-eth:8545
  ETH_WS_URL: ws://evm-node-eth:8546
  SUBSTRATE_RPC_URL: ws://collator-01:9944
  # contracts
  CHAIN_ID: "1337"
  AVS_REGISTRY_COORDINATOR_ADDR: 0x851356ae760d987E095750cCeb3bC6014560891C
  # AVS
  AVS_SERVER_IP_PORT_ADDRESS: 0.0.0.0:8090
  AVS_BLOCK_VALIDATION_PERIOD: "5"
  # OP
  RUST_LOG: info
  AVS_RPC_URL: http://avs-aggregator:8090
  TESTNET: "true"
  ECDSA_EPHEMERAL_KEY: "true"
  BLS_EPHEMERAL_KEY: "true"

envArb:
  # rpc
  ETH_RPC_URL: http://evm-node-arb:8545
  ETH_WS_URL: ws://evm-node-arb:8546
  SUBSTRATE_RPC_URL: ws://collator-01:9944
  # contracts
  CHAIN_ID: "1337"
  AVS_REGISTRY_COORDINATOR_ADDR: 0x851356ae760d987E095750cCeb3bC6014560891C
  # AVS
  AVS_SERVER_IP_PORT_ADDRESS: 0.0.0.0:8090
  AVS_BLOCK_VALIDATION_PERIOD: "5"
  # OP
  RUST_LOG: info
  AVS_RPC_URL: http://avs-aggregator:8090
  TESTNET: "true"
  ECDSA_EPHEMERAL_KEY: "true"
  BLS_EPHEMERAL_KEY: "true"

######################
# aggregator configs #
######################
aggregatorEnabled: true
# Override the image tag provided on deployment from IMAGE_TAG env variable
aggregatorImageTag: 5d6f2a4db68e0601f14b3ced43773488efdda164

aggregatorEnvSecrets:
  ECDSA_KEY_JSON: ref+sops://secrets.enc.yaml#/testnetAggregatorEcdsaKeyJson
  ECDSA_KEY_PASSWORD: ref+sops://secrets.enc.yaml#/testnetAggregatorEcdsaKeyPassword
  ETH_RPC_URL: ref+sops://secrets.enc.yaml#/holeskyEthereumHttpsUrl
  ETH_WS_URL: ref+sops://secrets.enc.yaml#/holeskyEthereumWssUrl
aggregatorEnv:
  SUBSTRATE_RPC_URL: ws://collator-01:9944
  CHAIN_ID: "17000"
  AVS_BLOCK_VALIDATION_PERIOD: '100'
  AVS_DEBOUNCE_RPC: '20'
  AVS_DEPLOYMENT_BLOCK: '1233400'
  AVS_KICK_PERIOD: '25'
  AVS_REGISTRY_COORDINATOR_ADDR: '0xfd6A45621DDfeBF94C082e60E0De92aA305a97a1'
  AVS_RPC_URL: http://avs-aggregator:8090
  AVS_SERVER_IP_PORT_ADDRESS: 0.0.0.0:8090
  AVS_TASK_EXPIRATION: '300'
  AVS_UPDATE_STAKE_PERIOD: '150'
  OPT_IN_AT_STARTUP: 'true'
  LOG_LEVEL: 'info'
  RUST_LOG: avs=debug

#####################
# finalizer configs #
#####################
finalizerEnabled: true
# Override the image tag provided on deployment from IMAGE_TAG env variable
finalizerImageTag: ba3aaf237234092ad21bf0a4c5ff0f08523ba6f0

finalizerEnvSecrets:
  ECDSA_KEY_JSON: ref+sops://secrets.enc.yaml#/testnetFinalizerEcdsaKeyJson
  ECDSA_KEY_PASSWORD: ref+sops://secrets.enc.yaml#/testnetFinalizerEcdsaKeyPassword
  BLS_KEY_JSON: ref+sops://secrets.enc.yaml#/testnetFinalizerBlsKeyJson
  BLS_KEY_PASSWORD: ref+sops://secrets.enc.yaml#/testnetFinalizerBlsKeyPassword
  ETH_RPC_URL: ref+sops://secrets.enc.yaml#/holeskyEthereumHttpsUrl
  ETH_WS_URL: ref+sops://secrets.enc.yaml#/holeskyEthereumWssUrl
finalizerEnv:
  SUBSTRATE_RPC_URL: ws://collator-01:9944
  CHAIN_ID: "17000"
  AVS_BLOCK_VALIDATION_PERIOD: '100'
  AVS_DEBOUNCE_RPC: '20'
  AVS_DEPLOYMENT_BLOCK: '1233400'
  AVS_KICK_PERIOD: '25'
  AVS_REGISTRY_COORDINATOR_ADDR: '0xfd6A45621DDfeBF94C082e60E0De92aA305a97a1'
  AVS_RPC_URL: http://avs-aggregator:8090
  AVS_SERVER_IP_PORT_ADDRESS: 0.0.0.0:8090
  AVS_TASK_EXPIRATION: '300'
  AVS_UPDATE_STAKE_PERIOD: '150'
  OPT_IN_AT_STARTUP: 'true'
  LOG_LEVEL: 'info'
  RUST_LOG: avs=debug,ether=trace

###########################
# rollup-updater configs #
###########################
updaterEnabled: true
# Override the image tag provided on deployment from IMAGE_TAG env variable
updaterImageTag: 028fcb899a6e4be1be008b0f063f2a9d15bfe07b

updaterChainUrlEth: ref+sops://secrets.enc.yaml#/holeskyEthereumHttpsUrl
updaterMnemonicEth: ref+sops://secrets.enc.yaml#/updaterMnemonicEth
updaterEnvEth:
  CHAIN: "holesky"
  L1_CHAIN: "Ethereum"
  MANGATA_NODE_URL: ws://collator-01:9944
  EIGEN_CONTRACT_ADDRESS: "0x0000000000000000000000000000000000000000"
  MANGATA_CONTRACT_ADDRESS: "0x93de6a193A839218BCA00c8D478256Ac78281cE3"
  FINALIZATION_SOURCE: "relay"
  LIMIT: "25"

updaterChainUrlArb: ref+sops://secrets.enc.yaml#/sepoliaArbitrumHttpsUrl
updaterMnemonicArb: ref+sops://secrets.enc.yaml#/updaterMnemonicArb
updaterEnvArb:
  CHAIN: "arbitrum"
  L1_CHAIN: "Arbitrum"
  MANGATA_NODE_URL: ws://collator-01:9944
  EIGEN_CONTRACT_ADDRESS: "0x0000000000000000000000000000000000000000"
  MANGATA_CONTRACT_ADDRESS: "0x998AaF69F731009d4E2d470E974766F1EB8f5142"
  FINALIZATION_SOURCE: "relay"
  LIMIT: "25"

############################
# rollup-sequencer configs #
############################
sequencerEnabled: true
secondSequencerEnabled: false
# Override the image tag provided on deployment from IMAGE_TAG env variable
sequencerImageTag: b4eac04bc26af897711c74a4309d5c659178d75f

firstSequencerMnemonicEth: "0x8075991ce870b93a8870eca0c0f91913d12f47948ca0fd25b49c6fa7cdbeee8b"
secondSequencerMnemonicEth: "bottom drive obey lake curtain smoke basket hold race lonely fit walk//Bob"
sequencerChainUrlEth: ref+sops://secrets.enc.yaml#/holeskyEthereumHttpsUrl
sequencerEnvEth:
  L1_CHAIN: "Ethereum"
  MANGATA_NODE_URL: ws://collator-01:9944
  MANGATA_CONTRACT_ADDRESS: "0x93de6a193A839218BCA00c8D478256Ac78281cE3"
  LIMIT: "100"

firstSequencerMnemonicArb: "0x0b6e18cafb6ed99687ec547bd28139cafdd2bffe70e6b688025de6b445aa5c5b"
secondSequencerMnemonicArb: "bottom drive obey lake curtain smoke basket hold race lonely fit walk//Bob"
sequencerChainUrlArb: ref+sops://secrets.enc.yaml#/sepoliaArbitrumHttpsUrl
sequencerEnvArb:
  L1_CHAIN: "Arbitrum"
  MANGATA_NODE_URL: ws://collator-01:9944
  MANGATA_CONTRACT_ADDRESS: "0x998AaF69F731009d4E2d470E974766F1EB8f5142"
  LIMIT: "100"
  
